install.packages("tidyr")
install.packages("dplyr")
install.packages("plyr")
install.packages("grid")
install.packages("gridExtra")
install.packages("ggplot2")
install.packages("ggpubr")
install.packages("ggsci")
install.packages("Hmisc")
install.packages("RColorBrewer")
install.packages("ggrastr")

install.packages("BiocManager")
#BiocManager::install("GenomicRanges")
BiocManager::install("EmpiricalBrownsMethod")